### PR TITLE
Tvdb UI classes rework + profile command + view error handling

### LINKED ISSUE #27: Add /profile [user] command
This task requires basic TvDB support and database to be completed.

The /profile command should show the user's favorite shows / movies, amount of total shows added and whatever other things that come to mind.

Requires #22 #31

### LINKED ISSUE #73: The View Episodes button on `/search` also shows up for movies. It should be reactive.

### PR DESCRIPTION
**Pull request by ItsDrike**

### CODE REVIEW

**Comment by ItsDrike** [comment]
I'm marking this as ready for review, even though the /profile command definitely isn't complete, in fact there are a lot of improvements that it definitely needs, however, to speed development up, I'd like the reworked classes to get merged as soon as possible, as it will affect development of other things. The profile command can be finished later.

**Comment by ItsDrike** [comment]
@Paillat-dev feel free to push any changes into this, as you'll probably wake up much sooner than I will and I don't want to block anything here. Do note though that if you will decide to push here, you will not be able to get an approving review for this PR that would make it mergeable. So you'd need to wait for me. Alternatively, you can just merge this and open another PR with any changes you'd like to make. *Even more alternatively*, you can work off of this branch (even after you've pushed to it), leaving the PR opened but still getting the benefit of working off of these changes.

**Comment by Paillat-dev** [comment]
I adapted it to use the new system for series,  but it doesn't work because the relationship on UserListtem.episode returns none.

**Review by Paillat-dev — APPROVED** [review]
This is amazing

**Pull request merged**
